on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Login to Github Packages"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
        name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.actor }}/${{ github.repo }}:latest